variables:
  IMAGE_PATH: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}

stages:
  - build
  - deploy

docker-build:
  stage: build
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^qa-\d+.\d+.\d+-?.*$/
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
  script:
    - docker build -f "./Dockerfile" --force-rm -t ${IMAGE_PATH} .
    - docker push ${IMAGE_PATH}
  after_script:
    - docker logout ${CI_REGISTRY}

k8s-deploy:
  stage: deploy
  when: manual
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^qa-\d+.\d+.\d+-?.*$/
  image:
    name: lwolf/helm-kubectl-docker:latest
    entrypoint: [""]
  script:
    - kubectl config use-context ${KUBE_CONTEXT}
    - helm version
    - helm repo add medulla --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_API_V4_URL}/projects/79/packages/helm/stable
    - helm repo update
    - helm upgrade --install --namespace ${DEFAULT_K8S_NAMESPACE} --history-max 5 --set image.tag=${CI_COMMIT_TAG} ${CI_PROJECT_NAME} -f ./devEnvValues.yml medulla/generic
  dependencies:
    - docker-build
